# Generated by Django 3.1 on 2021-09-05 10:14

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatesystSteroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steroid_type', models.CharField(choices=[('hydrocortisone20mg', 'hydrocortisone20mg'), ('perdinslone5mg', 'perdinslone5mg'), ('methylperdinslon4mg', 'methylperdinslon4mg'), ('triamcinlone4mg', 'triamcinlone4mg'), ('dexamethasone.75mg', 'dexamethasone.75mg'), ('betamethasone.6mg', 'betamethasone.6mg')], max_length=250)),
                ('perdinslone5mg', models.IntegerField()),
                ('methylperdinslon4mg', models.IntegerField()),
                ('triamcinlone4mg', models.IntegerField()),
                ('dexamethason75mg', models.IntegerField()),
                ('betamethasone6mg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('name', models.CharField(default='Empty', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('decline', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('preparation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manufacturer', models.CharField(max_length=100)),
                ('genric', models.CharField(max_length=300)),
                ('form', models.CharField(max_length=300)),
                ('conecentarion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesion_site', models.CharField(choices=[('1', 'head-neck'), ('2', 'face'), ('2', 'hand'), ('3', 'scalp'), ('4', 'trunk'), ('4', 'foot'), ('5', 'lower_limbs'), ('6', 'upper_limb'), ('7', 'BUTTOCK'), ('8', 'AXILLA'), ('9', ' UPPER THIGH'), ('10', 'CHEST')], max_length=200)),
                ('location_site_image', models.ImageField(default='default.jpg', upload_to='location_pics')),
                ('lesion_number', models.IntegerField(default=1)),
                ('lesion_size', models.CharField(max_length=200)),
                ('Biopsy_Request', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Biopsy Request')),
                ('signature', models.BinaryField(blank=True, null=True)),
                ('Diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.diagnosis')),
                ('dermatologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorvisits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
            options={
                'verbose_name_plural': 'PatientVisit',
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='XRay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xrays/')),
                ('name', models.CharField(default='name', max_length=100)),
                ('predictions', models.TextField(default='')),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='documents/')),
                ('text', models.TextField(default='')),
                ('name', models.CharField(default='name', max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('power', models.PositiveIntegerField(max_length=100)),
                ('route', models.CharField(max_length=1000)),
                ('dosages_interval', models.PositiveIntegerField()),
                ('amount', models.CharField(default=0, max_length=1000)),
                ('medicine', models.ManyToManyField(to='clinic.Medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
                ('patientVisit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patientvisit')),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=225)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lab_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.labrequest')),
            ],
        ),
        migrations.AddField(
            model_name='labrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.labtest'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(default='this is a default message.')),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('status', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.invoice')),
            ],
        ),
    ]
